### PR TITLE
Fix: small edits to the readme file

### PR DESCRIPTION
**Pull request by lwasser**
hi @jarrodmillman ! 👋 i had a few issues running this as the commands were slightly different from what was in the README file. This PR just updates the README to better explain how to run this!!

One question - i did NOT have to install from the requirements.txt to get this to run. it seemed as if the deps installed when i ran `pip install -e .` Should we remove that section as well from the README?

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Comment by munkm** [comment]
> One question - i did NOT have to install from the requirements.txt to get this to run. it seemed as if the deps installed when i ran pip install -e . Should we remove that section as well from the README?

It looks like all of the dependencies that were previously defined in `requirements.txt` in the devstats-data directory are now in the `pyproject.toml` file in this repo. We should probably update the README with updated installation directions.

**Comment by lwasser** [comment]
do y'all want the `pre-commit.ci` bot to lint for you here? if so i'm happy to open an issue and set it up. if y'all don't like the bot i can skip. i will setup pre-commit locally. I missed it as it wasn't in the readme. i can also add info about pre-commit to the readme for other users / potential contributors.

**Comment by munkm** [comment]
> i can also add info about pre-commit to the readme for other users / potential contributors.

That would be awesome! Anything that helps make this more accessible to contribute to would be wonderful. 

I don't have strong feelings about the bot, so I will defer to others for that decision.

**Comment by lwasser** [comment]
ok i added it. lemme fix the linting situation next. the bot is really nice for fly by contributions if people are onboard ... i'll open an issue.

**Comment by stefanv** [comment]
Thanks @lwasser!

**Pull request merged**
